### ISSUE TITLE
Pressing TAB or arrow key throws TypeError with simple example from GitHub

### ISSUE THREAD

**Issue by ZipBrandon** [tomsouthall/turnstone#3]
This may be related to #2 but when I press TAB or arrow key it throws an TypeError. 

https://codesandbox.io/s/hidden-breeze-lre13y

![image](https://user-images.githubusercontent.com/68867795/160155415-f9f4760f-28a3-45a6-a755-9deca6f59947.png)

**Comment by tomsouthall** [comment]
I have found the cause and will be releasing a fix shortly

**Comment by tomsouthall** [comment]
Fixed in v1.2.2. Thanks for flagging this.

**Comment by tomsouthall** [comment]
Here is your example updated with the latest version which fixes the issue

https://codesandbox.io/s/tender-hopper-kql1rr
